version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mikrotik-tio
    ports:
      - "8000:8000"
    networks:
      - laravel_network
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000
    restart: always
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=192.168.100.7
      - DB_PORT=3306
      - DB_DATABASE=mikrotik_app
      - DB_USERNAME=root
      - DB_PASSWORD=Baragajul

networks:
  laravel_network:
    driver: bridge
