version: '3'
services:
  app:
    image: laravel
    container_name: laravel_app
    ports:
      - "8000:8000"
    networks:
      - laravel_network
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000
    restart: always

networks:
  laravel_network:
    driver: bridge
